### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aschrijver** [brandonsides/pubblr#4]
Hi there. I was curious about the license you'll choose to open source with. I maintain the fedi-related lists at https://delightful.club and those track only FOSS projects.

**Comment by brandonsides** [comment]
@aschrijver I am currently planning on using the MIT license!

**Comment by brandonsides** [comment]
Added license

**Comment by aschrijver** [comment]
Thank you! I have lined this project up for inclusion on the list (I work from some kind of backlog :)
